import createClient from "openapi-fetch";
import type { paths } from "./schema.ts"; // generated by openapi-typescript

export const client = createClient<paths>({
    baseUrl: "https://musicfun.it-incubator.app/api/1.0/",
    headers: {
    'api-key': 'b9b93a14-5751-4e3b-a9c4-4e1503c25972'
} });